version: "3.8"

services:
  node:
    image: ${COMPOSE_PROJECT_NAME}/node:16-alpine
    build: ./images/node
    restart: on-failure
    command: /bin/sh -c "npm run start"
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ../:/var/www
    environment:
      - PORT=${APP_PORT}
